//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safricom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string business_name { get; set; }
        public string cell_phone_one { get; set; }
        public string telephone_work { get; set; }
        public string email { get; set; }
        public string id_passport { get; set; }
        public string vat_registration { get; set; }
    }
}
