//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safricom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientaddress
    {
        public int id { get; set; }
        public string street_number { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string suburb { get; set; }
        public string gps_coordinates { get; set; }
        public string post_box { get; set; }
        public string postal_code { get; set; }
        public string type { get; set; }
        public Nullable<int> client_id { get; set; }
    }
}
