//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safricom.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class radiusEntities : DbContext
    {
        public radiusEntities()
            : base("name=radiusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<radacct> radaccts { get; set; }
        public DbSet<radcheck> radchecks { get; set; }
        public DbSet<radgroupcheck> radgroupchecks { get; set; }
        public DbSet<radgroupreply> radgroupreplies { get; set; }
        public DbSet<radpostauth> radpostauths { get; set; }
        public DbSet<radreply> radreplies { get; set; }
        public DbSet<radusergroup> radusergroups { get; set; }
    }
}
